version: 2.1
orbs:
  # Newman orb for calling APIs + executing API tests from the POTMAN collection.
  newman: postman/newman@1.0.0
jobs:
  newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./api-tests-demo.postman_collection.json
          environment: ./kubric.postman_globals.json
          timeout: '1000'
