# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  # Newman orb for calling APIs + executing API tests from the POTMAN collection.
  newman: postman/newman@0.0.2
# Orchestrate or schedule a set of jobs
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run 
  api-automation-tests:
    # Run the welcome/run job in its own container
    jobs:
      newman-collection-run-env-timeout:
        executor: newman/postman-newman-docker
        steps:
          - checkout
          - newman/newman-run:
              collection: ./api-tests-demo.postman_collection.json
              environment: ./kubric.postman_globals.json
              timeout: '1000'
